### PR TITLE
Fix object variant name generation

### PR DESCRIPTION
**Pull request by iacore**
I just copy pasted the code for tuple and it works...

### CODE REVIEW

**Comment by yglukhov** [comment]
What does it fix though? Could you add a test for it?

**Comment by iacore** [comment]
This is required for https://github.com/yglukhov/ecs/pull/3. It makes this library usable for Nim 1.6.2. 

If you look at my commits, I just copied code from that for tuple. It works for some cases.

It's "buggy" because in some cases, the nim compiler breaks.

See example in https://github.com/nim-lang/Nim/issues/19516

**Comment by yglukhov** [comment]
It fails the tests. Try `nimble test`

**Comment by iacore** [comment]
Has new bug now. Don't merge yet.

**Comment by iacore** [comment]
I think it's ok now.

**Comment by yglukhov** [comment]
Thank you!

**Pull request merged**
